name: ResMiCo

on: [push, pull_request]

jobs:
  build:
    name: build (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ubuntu-latest
    env:
      DATADIR: data
    strategy:
      matrix:
        python-version: [3.9]
        build_type: [Release]
        compiler: [g++-9]
        include:
          - compiler: g++-9
            cxx: g++-9
            cc: gcc-9
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Checkout submodules
      run: git submodule update --init --recursive
    - name: bam2feat Create build dir
      run: mkdir ${{runner.workspace}}/ResMiCo/ResMiCo-SM/feature_extractor/build
    - name: bam2feat Configure CMake
      working-directory: ${{runner.workspace}}/ResMiCo/ResMiCo-SM/feature_extractor/build
      shell: bash
      run: |
        export CC=$(which ${{ matrix.cc }})
        export CXX=$(which ${{ matrix.cxx }})
        cmake .. -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
    - name: bam2feat Build
      working-directory: ${{runner.workspace}}/ResMiCo/ResMiCo-SM/feature_extractor/build
      shell: bash
      run: make -j
    - name: bam2feat Test
      working-directory: ${{runner.workspace}}/ResMiCo/ResMiCo-SM/feature_extractor/build
      shell: bash
      run: ./tests
    - uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: 'latest'
        auto-update-conda: true
        mamba-version: "*"
        python-version: ${{ matrix.python-version }}
        channels: conda-forge,bioconda
        activate-environment: resmico
    - name: conda env setup
      shell: bash -l {0}
      run: |
        conda info -a
        mamba env update -f conda_env.yaml python=${{ matrix.python-version }}
        conda list
        conda activate /usr/share/miniconda3/envs/resmico
        conda config --set channel_priority strict
    - name: cython contig reader
      shell: bash -l {0}
      working-directory: ${{runner.workspace}}/ResMiCo/resmico
      run: |
        python setup.py build_ext --inplace
    - name: pip install
      shell: bash -l {0}
      working-directory: ${{runner.workspace}}/ResMiCo/
      run: |
        pip install .
    - name: resmico tests
      shell: bash -l {0}
      working-directory: ${{runner.workspace}}/ResMiCo/resmico/tests
      run: |
        pytest -s --hide-run-results --script-launch-mode=subprocess
    - name: resmico readme example1
      shell: bash -l {0}
      working-directory: ${{runner.workspace}}/ResMiCo/
      run: |
        mkdir example1 && cd example1
        wget http://ftp.tue.mpg.de/ebio/projects/ResMiCo/UHGG-n9_bam2feat.tar.gz
        wget http://ftp.tue.mpg.de/ebio/projects/ResMiCo/UHGG-n9_bam2feat.md5
        md5sum --check UHGG-n9_bam2feat.md5
        tar -pzxvf UHGG-n9_bam2feat.tar.gz && rm -f UHGG-n9_bam2feat.*
        resmico bam2feat --outdir features UHGG-n9_bam2feat/map.tsv
        resmico evaluate --save-path predictions --save-name default-model --feature-files-path features
    - name: resmico readme example2
      shell: bash -l {0}
      working-directory: ${{runner.workspace}}/ResMiCo/
      run: |
        mkdir example2 && cd example2
        wget http://ftp.tue.mpg.de/ebio/projects/ResMiCo/UHGG-n9_features.tar.gz
        wget http://ftp.tue.mpg.de/ebio/projects/ResMiCo/UHGG-n9_features.md5
        md5sum --check UHGG-n9_features.md5
        tar -pzxvf UHGG-n9_features.tar.gz && rm -f UHGG-n9_features.*
        resmico evaluate --save-path predictions --save-name default-model --feature-files-path UHGG-n9_features/
        resmico filter --outdir filtered-contigs predictions/default-model.csv UHGG-n9_features/fasta/*fna.gz
    - name: resmico-sm tests
      working-directory: ${{runner.workspace}}/ResMiCo/ResMiCo-SM
      shell: bash -l {0}
      run: |
        wget http://ftp.tue.mpg.de/ebio/projects/ResMiCo/genomes_n10.tar.gz
        wget http://ftp.tue.mpg.de/ebio/projects/ResMiCo/genomes_n10.md5
        md5sum --check genomes_n10.md5
        tar -pzxvf genomes_n10.tar.gz && rm -f genomes_n10.tar.gz
        snakemake --use-conda -j 1 --force --quiet --dry-run
